### ISSUE TITLE
Strange head-feel when using Geicomo.com

### ISSUE THREAD

**Issue by qcsv** [Geicomo/Geicomo.com#2]
Hello. I am a long time user of Geicomo.com but recently I've noticed that every time I get this extreme sense of dread and despair when using the website. The more time I spend playing the "Click Game" the worse this feeling gets. I have also noticed ominous music and bell tolling especially around the 6-7 hour mark of playing the game.

**Comment by Pandemonious** [comment]
Hey cool website will check for updates ig
